### PR TITLE
use weak for supperior handling

### PR DESCRIPTION
**Pull request by LinusU**
Throws the error as soon as it's clear that it won't be handled in any way \o/

### CODE REVIEW

**Comment by LinusU** [comment]
It seems like Travis is failing because of an too old compiler :(

**Comment by LinusU** [comment]
@sindresorhus What do you think? :smile:

**Comment by LinusU** [comment]
The tests now only runs in io.js 1.4.1 and above since that was the version that introduced `unhandledRejection`.

**Comment by sindresorhus** [comment]
Really cool idea, but I don't want to introduce a native dependency. Native dependencies in Node are horrible and prone to break in so many ways and never works on Windows. Seeing how I'm planning to use this in most of my modules, I really don't want a native dependency in there.

**Comment by sindresorhus** [comment]
I encourage you to make it into an alternative module for those willing to have a native dependency, though.

**Comment by LinusU** [comment]
Sounds like a good plan, I'll try and finish up the other pull request then :)

**Comment by sindresorhus** [comment]
:+1:

**Pull request closed without merging**
